### ISSUE TITLE
Any way to add more than one devices to the same mollysocket server?

### ISSUE THREAD

**Issue by jayb-g** [pcrockett/mollysocket-fly#14]
Eg to let same fly instance support 2 or more devices without needing to have one instance for each device.

**Comment by pcrockett** [comment]
_I assume you're talking about adding another Signal account / another user to your instance._

Yup. Just go through the instructions starting at [step 3](https://github.com/pcrockett/mollysocket-fly/blob/main/doc/HOWTO.md#install-a-unifiedpush-distributor-on-your-android-phone) with your second device.

**Comment by pcrockett** [comment]
I'm not aware of any hard limit. Probably as many as your disk space / memory / CPU can handle (which is probably a pretty large amount).

I personally am supporting two Signal accounts on one instance without any issues.

**Comment by pcrockett** [comment]
Interesting. Never seen that before. Where are you seeing this error?

**Comment by pcrockett** [comment]
Ok. Well seeing how the URL in the error message is a `ntfy.sh` URL, my suspicion is that it was a transient error in the **ntfy** service. It doesn't look like it was an issue with MollySocket.

I am willing to bet that the ntfy error went away because the ntfy service scaled up or something, responding to heavy demand.

Just speculation. But in any case, I'm about 90% certain this isn't an issue with your instance of MollySocket.

I'll close this issue for now -- if you see any more strangeness, or find any more information to help debug the situation, feel free to re-open.
