### ISSUE TITLE
Troubleshoot missing notifications

### ISSUE THREAD

**Issue by eylenburg** [pcrockett/mollysocket-fly#6]
Hi, me again ;) 

I have noticed that notifications don't actually work unless I have the app open - turns out there is some error relating to ports I suppose? 

This is my output:

```
root@080ee7ef646748:/app# MOLLY_PORT=8021 mollysocket -v server
[2024-01-26T19:13:41Z INFO  mollysocket::config] No config file supplied
[2024-01-26T19:13:41Z INFO  rocket::launch] 🔧 Configured for release.
[2024-01-26T19:13:41Z INFO  rocket::launch::_] address: 127.0.0.1
[2024-01-26T19:13:41Z INFO  rocket::launch::_] port: 8021
[2024-01-26T19:13:41Z INFO  rocket::launch::_] workers: 1
[2024-01-26T19:13:41Z INFO  rocket::launch::_] max blocking threads: 512
[2024-01-26T19:13:41Z INFO  rocket::launch::_] ident: Rocket
[2024-01-26T19:13:41Z INFO  rocket::launch::_] IP header: X-Real-IP
[2024-01-26T19:13:41Z INFO  rocket::launch::_] limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
[2024-01-26T19:13:41Z INFO  rocket::launch::_] temp dir: /tmp
[2024-01-26T19:13:41Z INFO  rocket::launch::_] http/2: true
[2024-01-26T19:13:41Z INFO  rocket::launch::_] keep-alive: 5s
[2024-01-26T19:13:41Z INFO  rocket::launch::_] tls: disabled
[2024-01-26T19:13:41Z INFO  rocket::launch::_] shutdown: ctrlc = true, force = true, signals = [SIGTERM], grace = 2s, mercy = 3s
[2024-01-26T19:13:41Z INFO  rocket::launch::_] log level: critical
[2024-01-26T19:13:41Z INFO  rocket::launch::_] cli colors: true
[2024-01-26T19:13:41Z INFO  rocket::launch] 📬 Routes:
[2024-01-26T19:13:41Z INFO  rocket::launch::_] (discover) GET /
[2024-01-26T19:13:41Z INFO  rocket::launch::_] (register) POST / application/json
[2024-01-26T19:13:41Z INFO  rocket::launch::_] GET /metrics/
[2024-01-26T19:13:41Z INFO  rocket::launch] 📡 Fairings:
[2024-01-26T19:13:41Z INFO  rocket::launch::_] Shield (liftoff, response, singleton)
[2024-01-26T19:13:41Z INFO  rocket::launch::_] Prometheus metric collection (request, response)
[2024-01-26T19:13:41Z ERROR rocket::error] Rocket failed to bind network socket to given address/port.
[2024-01-26T19:13:41Z INFO  rocket::error::_] Address already in use (os error 98)
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket-0.5.0/src/error.rs:279:9:
aborting due to socket bind error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I also create an issue here but I'm not sure if this is an issue with Mollysocket in general or with Mollysocket-Fly specifically: https://github.com/mollyim/mollysocket/issues/24

**Comment by pcrockett** [comment]
The short of it is:

* Your server is already running the mollysocket service
* When you log in and run `mollysocket -v server`, you are trying to run a _second_ instance of the mollysocket service
* Since the first instance is still running, your command will fail. You can't (and don't want to) run two instances at the same time _( technically not true, but close enough)._

In other words: This error message has absolutely nothing to do with notifications not working.

---

If you want to troubleshoot your notifications, you might want to look more in the direction of:

* `mollysocket connection list` -- this will give you information like current connection UUIDs
* `mollysocket test uuid <a_uuid_from_above_command>` -- gives you status information about connections

though honestly these two commands have never helped me.

What HAS helped me is actually [turning on `ntfy.sh` logging](https://docs.ntfy.sh/troubleshooting/#android-app) on my Android phone.

I encountered a similar issue where I was receiving notifications on one device, but not another. I turned on `ntfy.sh` logging on the device that was having issues, and got relevant errors in the logs. You can see the bug issue I filed here:

https://github.com/binwiederhier/ntfy/issues/997

It would be interesting to see if you have the same issue. I am betting this might be a MollySocket bug rather than a `ntfy.sh` bug.

**Comment by eylenburg** [comment]
For now I just decided to destroy the app and launch it again. With ntfy logs on. It looks like it's working right now:

```
1706543505148 2024-01-29 15:51:45.148 D NtfyUpBroadcastRecv Adding subscription with for app im.molly.app.unifiedpush (connectorToken <removed>): Subscription(id=<removed>, baseUrl=https://ntfy.sh, topic=<mollysocket>, instant=true, mutedUntil=0, minPriority=0, autoDelete=-1, insistent=-1, lastNotificationId=null, icon=null, upAppId=im.molly.app.unifiedpush, upConnectorToken=<removed>, displayName=null, dedicatedChannels=false, totalCount=0, newCount=0, lastActive=1706543505, state=NOT_APPLICABLE)
1706543505155 2024-01-29 15:51:45.155 D NtfyUpDistributor Sending NEW_ENDPOINT to im.molly.app.unifiedpush (token=<removed>): https://ntfy.sh/<mollysocket>?up=1
1706543505273 2024-01-29 15:51:45.273 D NtfySubscriberService - Desired connections: [ConnectionId(baseUrl=https://ntfy.sh, topicsToSubscriptionIds={<mollysocket>=<removed>, <element>=<removed>})]
1706543505274 2024-01-29 15:51:45.274 D NtfySubscriberService - New connections: [ConnectionId(baseUrl=https://ntfy.sh, topicsToSubscriptionIds={<mollysocket>=<removed>, <element>=<removed>})]
1706543505280 2024-01-29 15:51:45.280 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] Starting connection for subscriptions: {<mollysocket>=<removed>, <element>=<removed>}
1706543505280 2024-01-29 15:51:45.280 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] (Re-)starting connection for subscriptions: {<mollysocket>=<removed>, <element>=<removed>}
1706543505280 2024-01-29 15:51:45.280 D NtfyApiService Opening subscription connection to https://ntfy.sh/<mollysocket>,<element>/json?since=none
1706543505281 2024-01-29 15:51:45.281 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] Connection is active (failed=false, callCanceled=false, jobActive=true, serviceStarted=true
1706543535287 2024-01-29 15:52:15.287 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] Connection is active (failed=false, callCanceled=false, jobActive=true, serviceStarted=true
1706543640921 2024-01-29 15:54:00.921 D NtfySubscriberService - New connections: [ConnectionId(baseUrl=https://ntfy.sh, topicsToSubscriptionIds={<mollysocket>=<removed>, <element>=<removed>})]
1706543640921 2024-01-29 15:54:00.921 D NtfySubscriberService - Desired connections: [ConnectionId(baseUrl=https://ntfy.sh, topicsToSubscriptionIds={<mollysocket>=<removed>, <element>=<removed>})]
1706543640923 2024-01-29 15:54:00.923 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] Starting connection for subscriptions: {<mollysocket>=<removed>, <element>=<removed>}
1706543640924 2024-01-29 15:54:00.924 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] (Re-)starting connection for subscriptions: {<mollysocket>=<removed>, <element>=<removed>}
1706543640924 2024-01-29 15:54:00.924 D NtfyApiService Opening subscription connection to https://ntfy.sh/<mollysocket>,<element>/json?since=none
1706543640929 2024-01-29 15:54:00.929 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] Connection is active (failed=false, callCanceled=false, jobActive=true, serviceStarted=true
1706543670945 2024-01-29 15:54:30.945 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] Connection is active (failed=false, callCanceled=false, jobActive=true, serviceStarted=true
1706543709567 2024-01-29 15:55:09.567 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] Connection is active (failed=false, callCanceled=false, jobActive=true, serviceStarted=true
1706543774051 2024-01-29 15:56:14.051 D NtfySubscriberConn [https://ntfy.sh/<mollysocket>,<element>] Connection is active (failed=false, callCanceled=false, jobActive=true, serviceStarted=true
1706543782045 2024-01-29 15:56:22.045 D NtfySubscriberService - Desired connections: [ConnectionId(baseUrl=https://ntfy.sh, topicsToSubscriptionIds={<mollysocket>=<removed>, <element>=<removed>})]
1706543782045 2024-01-29 15:56:22.045 D NtfySubscriberService - Active connections: [ConnectionId(baseUrl=https://ntfy.sh, topicsToSubscriptionIds={<mollysocket>=<removed>, <element>=<removed>})]
```

(These are just the lines mentioning the Mollysocket topic ID. I have removed all topic IDs and tokens, not sure if these are sensitive or not.)

I have restarted the phone, not launching Molly, and sending a message from another phone number, and it worked. Not sure what's the best way to really test UP notifications otherwise.

By the way, when I ran your tutorial again, I could not use `make launch`. I just got a suggestion to install the package `make` from the repo...

So I just used the first command from the Makefile (`flyctl launch --copy-config --no-public-ips --yes`) and that seemed to work instead.

**Comment by eylenburg** [comment]
Actually it seems like notifications _don't_ come through on time. Even though I can't find anything wrong in the ntfy logs (saying there's an active connection to the topic) or `mollysocket test uuid` ("UUID is valid. A connection is associated to this UUID and is ok.")

**Comment by pcrockett** [comment]
You say they don't come through "on time," do you mean they still come via ntfy.sh but are significantly delayed? By how long?

That makes me think about [ntfy's _instant delivery_ feature](https://docs.ntfy.sh/subscribe/phone/#instant-delivery), which may not be turned on if you installed `ntfy.sh` from the Google Play store.

> Without instant delivery, messages may arrive with a significant delay (sometimes many minutes, or even hours later).

However if you installed from [F-Droid](https://f-droid.org/en/packages/io.heckel.ntfy/) then you're probably using instant delivery no matter what, so that may not be the issue.

**Comment by eylenburg** [comment]
I dont think they come through at all. Basically I was waiting for a minute after sending the test message, then gave up. When I open Molly, the notification comes. With Websocket it's no problem at all.

I use ntfy from F-Droid

**Comment by pcrockett** [comment]
Mollysocket has a new "ping" feature that should help troubleshoot problems like this. I'm going to close this issue for now, and if there are still problems with missing notifications, we can start a new one.

**Comment by jayb-g** [comment]
@eylenburg same issue. Notifications stop after device inactivity of around 2 mins(ie doze mode?).

Messages sent to it be only at _sent_ and don't get _delivered_, ie only single tick shown at sender.

At this point, running `mollysocket connection ping {uuid}` works successfully and notifies test message. But actual messages still remain undelivered. 

Although when doing `curl -d 'test' https://ntfy.sh/foobar?up=1` all messages are received instantly(either that or when molly is opened)

I have no idea what's causing the issue or how fly.io works but for me, solution was to run `fly deploy` after the issue(or maybe after once mollysocket is fully setup)and it fixed the issue. Working good so far since last 24hours.

Tested this twice. Same issue. Same solution.

@pcrockett amazing and helpful repo, having some mechanism to keep both mollysocket and fly.io system up to date would be great, since most people even if techie, wouldn't want to monitor/troubleshoot/update this setup on regular basis just to get notifications on time.

**Comment by pcrockett** [comment]
@jayb-g this is such great feedback, thank you! i created separate issues (see ☝️) for your various comments. they are all worth addressing (and i already addressed the webserver one).

now i have the feeling like we're making progress on the missing notifications, will continue pulling that thread in #8
