### ISSUE TITLE
Exposing a web service

### ISSUE THREAD

**Issue by fillwithjoy1** [pcrockett/mollysocket-fly#7]
Given that Mollysocket's web server relies on it being exposed to the world wide web, it's possible that the guide can be updated without needing to turn on air-gapped mode

**Comment by pcrockett** [comment]
Hey, thanks for the suggestion.

Running in air-gapped mode or normal mode is a tradeoff decision. I have chosen to run in air-gapped mode because, while less convenient, it is more secure.

I could update the guide to include normal mode, however that also means I'd need to test / maintain it. Since I don't run it in normal mode, I'd rather not change the guide.

However if someone were to create a fork of this project that supports normal mode, I would be happy to link to it at the top of the guide.
